name: 🐛 Bug
description: Report any issue with MCP Community
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please explain what you're seeing and what you would expect to see.
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Python, MCP Community & OS Versions, related packages (not required)
      description: |
        Which version of Python and MCP Community are you using? Which Operating System?

      render: TOML
